### ISSUE TITLE
Add comment section

### ISSUE THREAD

**Issue by Orpheusp** [BobbyAbroad/abroad-blog-src#1]
plz :)

**Comment by bobbylcraig** [comment]
Hey Wei,

This thing isn't even close to finished. Honestly, I haven't even released it to anyone because I want to finish it before doing so. It still needs:
- Comment section (not sure if per post or for the entire blog) probably via Disqus
- Photos
- Another page explaining who people are, because it can get confusing
- I need to write the rest of the posts...

Let me know if you have any more ideas. I'll probably finish around mid-June.

**Comment by Orpheusp** [comment]
Sorry to excavate this premature hidden gem, but could you also add a page/post explaining how you build the blog? Also, accidentally found an interesting point called “Edinburgh” in the map file. Does that mean we are getting a post about Edinburgh <3 ?

**Comment by bobbylcraig** [comment]
I will, but that'll probably be found on http://bobbylcraig.com and linked to from the blog page? And it'll probably be considerably later...ain't nobody got time for that! And possibly (to Edinburgh)...I want to visit someone there but time (and funds) might prohibit that.

Hope all is well on the hill! I'm still coming to visit you and Andy on the coast next year so be prepared!

**Comment by bobbylcraig** [comment]
@Orpheusp, there is now a comment section for each post. I'm not going to add one for the entire thing...that sounds too forum-like for my liking. Still have lots to do, but I'm closing this issue :)
